name: Test and Deploy

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8

      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: RAILS_ENV=test bundle exec rails assets:precompile

      - run: bundle exec rails test
